export type TrackId = 'A' | 'B'

export type ItemKind = 'course' | 'free' | 'practice' | 'milestone'

export interface Item {
  id: string
  track: TrackId
  kind: ItemKind
  title: string
  /** Инструктор, язык, пометки — выводится серым рядом с названием */
  meta?: string
  /** Что проходить, что пропускать, зачем */
  note: string
  /** Часы работы с практикой (то, что идёт в расписание) */
  hours: number
  /** Чистая длительность видео на Udemy, если есть */
  video?: number
  /** Коэффициент видео → работа, для подписи */
  factor?: number
  /** Необязательный шаг: можно снять галочкой «пропустить» */
  optional?: boolean
  /** Уже пройдено (Tilda) */
  done?: boolean
  /** Ссылка на сам материал: страница курса на Udemy, плейлист на YouTube, документация */
  url?: string
  /** Сколько в материале считаемых единиц — уроков, разделов, видео. Без него прогресс идёт в процентах */
  units?: number
  /** Как называть единицы в подписи «из 123 …» */
  unitWord?: string
  /** Сколько единиц пройдено на момент составления плана; дальше правится вручную и хранится в браузере */
  unitsDone?: number
  /** Польза шага для цели трека, 0–100: не «хороший ли курс», а насколько приближает к заказам или офферу за свои часы */
  value?: number
}

export interface Habit {
  track: TrackId
  time: string
  text: string
}

export interface Track {
  id: TrackId
  name: string
  goal: string
  color: string
}

export const TRACKS: Track[] = [
  {
    id: 'A',
    name: 'Фриланс — деньги как можно быстрее',
    goal: '70 тыс. ₽/мес на русских биржах по стеку verno-dev.com, потом зарубежные клиенты',
    color: 'var(--track-a)',
  },
  {
    id: 'B',
    name: 'Рост как программиста — fullstack',
    goal: 'TypeScript → Node/Express → БД → Docker → Next.js, пет-проект в портфолио, удалёнка за рубежом',
    color: 'var(--track-b)',
  },
]

/** Дата возвращения в вуз — после неё темп падает */
export const UNI_DATE = '2027-02-09'

/** Понедельник, с которого стартует план по умолчанию */
export const DEFAULT_START = '2026-09-07'

export const ITEMS: Item[] = [
  // ───────────────────────── Трек A — фриланс ─────────────────────────
  {
    id: 'a-tilda',
    track: 'A',
    kind: 'course',
    title: 'Создание сайтов и веб-дизайн в Tilda',
    meta: 'Фокеев · 14,5 ч видео · пройдено на 100 %',
    note: 'Лендинги 7–26 тыс. ₽ и бизнес-сайты 12–48 тыс. ₽ по прайсу verno-dev.com можно брать с сегодняшнего дня. Курсы ниже расширяют чек, а не открывают доступ к заказам.',
    hours: 0,
    value: 85,
    video: 14.5,
    done: true,
    url: 'https://www.udemy.com/course/tilda-essential/',
  },
  {
    id: 'a-stepik-wp-nocode',
    track: 'A',
    kind: 'course',
    title: 'Курс по WordPress с нуля до результата — сайты без кода',
    meta: 'Фокеев · Stepik · 90 из 95 шагов',
    note: 'Пройден на 95 %: вместе с Tilda это второй готовый стек под лендинги и бизнес-сайты из прайса. Оставшиеся пять шагов закрой при первом же заказе на WordPress.',
    hours: 0,
    value: 90,
    done: true,
    url: 'https://stepik.org/course/208466',
  },
  {
    id: 'a-stepik-verstka',
    track: 'A',
    kind: 'course',
    title: 'Вёрстка и веб-разработка сайтов — с нуля и продвинутый уровень',
    meta: 'Фокеев · Stepik · два курса, 126 из 137 и 103 из 134 шагов',
    note: 'Оба курса по вёрстке закрыты: HTML, CSS, адаптив и JavaScript для лендингов у тебя есть. Это база и для Webflow, и для WordPress по коду, и для макетов из Figma.',
    hours: 0,
    value: 95,
    done: true,
    url: 'https://stepik.org/course/114109',
  },
  {
    id: 'a-sales-kit',
    track: 'A',
    kind: 'practice',
    title: 'Набор продавца: ТЗ, договор, предоплата, шаблоны откликов',
    note: 'Шаблон технического задания, короткий договор-оферта, правило «50 % предоплаты», три шаблона отклика под лендинг / бизнес-сайт / магазин. Один вечер, а потом экономит часы на каждом заказе и режет число невыгодных клиентов.',
    hours: 4,
    value: 95,
  },
  {
    id: 'a-stepik-10-sites',
    track: 'A',
    kind: 'course',
    title: 'Верстаем 10 сайтов по макету из Figma в портфолио',
    meta: 'Фокеев · Stepik · 507 шагов',
    note: 'Единственный курс в библиотеке, который сам по себе даёт портфолио: десять готовых сайтов по макетам. Ровно этого треку A не хватало — заказы приходят с кейсов, а не с сертификатов. По одному сайту в неделю параллельно с WordPress, каждый готовый сразу в кейсы на verno-dev.com.',
    hours: 31,
    value: 95,
    units: 507,
    unitWord: 'шагов',
    unitsDone: 35,
    url: 'https://stepik.org/course/123120',
  },
  {
    id: 'a-seo',
    track: 'A',
    kind: 'free',
    title: 'SEO-база для веб-разработчика',
    meta: 'Ulbi TV · 59 мин · плюс документация Google и Яндекса',
    note: 'Курса по SEO в библиотеке нет ни на Stepik, ни на Udemy. Вечер на разбор Ulbi TV — мета-теги, семантика, скорость, sitemap глазами разработчика, а не сеошника, — и вечер на документацию. Мета-теги и Open Graph, иерархия заголовков, скорость по Lighthouse, sitemap и robots, подключение Search Console и Яндекс Вебмастера. По сводкам парсера SEO стабильно в топ-3 запросов: после этого шага продаёшь «сайт с SEO-настройкой» вместо «сайта», а это плюс к чеку почти бесплатно.',
    hours: 4,
    value: 85,
    url: 'https://www.youtube.com/watch?v=JU79n3yU1aA',
  },
  {
    id: 'a-webflow',
    track: 'A',
    kind: 'course',
    title: 'Вёрстка и создание сайтов в Webflow',
    meta: 'Фокеев · 123 урока',
    note: 'Дальше — адаптив, SEO и экспорт проекта. Раздел 13 «Интернет-магазин» можно пропустить: Webflow-магазины в РФ почти не заказывают.',
    hours: 29,
    value: 40,
    video: 19,
    factor: 1.5,
    units: 123,
    unitWord: 'уроков',
    unitsDone: 94,
    url: 'https://www.udemy.com/course/webflow-s/',
  },
  {
    id: 'a-figma',
    track: 'A',
    kind: 'course',
    title: 'Веб-дизайн в Figma — с нуля, основы UX/UI',
    meta: 'Фокеев · выборочно',
    note: '~10 ч из 18: основы, цвет, AutoLayout (разделы 5 и 14), отступы, шрифты, дизайн-система и компоненты, адаптив, прототипирование, экспорт. Нужно, чтобы читать макеты заказчиков и рисовать простые лендинги самому. Картинки, маски, бонус по Photoshop — мимо.',
    hours: 15,
    value: 75,
    video: 10,
    factor: 1.5,
    units: 129,
    unitWord: 'уроков',
    unitsDone: 0,
    url: 'https://www.udemy.com/course/web-figma-ui/',
  },
  {
    id: 'a-theory',
    track: 'A',
    kind: 'course',
    title: 'Теория дизайна для веб-дизайнеров',
    meta: 'Фокеев',
    note: 'Короткий курс, поднимает качество лендингов, которые делаешь без дизайнера. Можно по вечерам параллельно с Webflow.',
    hours: 7,
    value: 55,
    video: 6,
    factor: 1.2,
    units: 61,
    unitWord: 'уроков',
    unitsDone: 0,
    url: 'https://www.udemy.com/course/cniiaptv/',
  },
  {
    id: 'a-stepik-wp-theme',
    track: 'A',
    kind: 'free',
    title: 'Сайт на WordPress: вёрстка и перенос на CMS',
    meta: 'Stepik · 307 шагов',
    note: 'Бесплатный курс про перенос своей вёрстки в тему WordPress. Пересекается с разделами Сокирки, поэтому по желанию: полезен, если хочешь пройти путь «макет → тема» до большого курса.',
    hours: 21,
    value: 35,
    optional: true,
    units: 307,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/113393',
  },
  {
    id: 'a-sochirca-1',
    track: 'A',
    kind: 'course',
    title: 'Весь WordPress и PHP, разделы 1–4',
    meta: 'Сокирка',
    note: 'База PHP (11 ч), кодекс темы (11 ч), практика темы (3 ч), кодекс плагинов (10 ч). Курс длится 244 ч — целиком не нужен, это ядро.',
    hours: 70,
    value: 85,
    video: 35,
    factor: 2,
    url: 'https://www.udemy.com/course/all-wordpress/',
  },
  {
    id: 'a-fse-woo',
    track: 'A',
    kind: 'free',
    title: 'Блочные темы и WooCommerce по документации',
    meta: 'developer.wordpress.org · демо-магазин',
    note: 'Двух вещей нет ни в одном купленном курсе. Блочные темы (FSE) — то, куда ушёл WordPress с версии 6.0: theme.json, шаблоны, паттерны, Site Editor; клиенты всё чаще приходят именно с такими сайтами, и чинить их по классическому PHP-шаблону не получится. WooCommerce у Сокирки есть, но он спрятан в разделах 5–7: 12 часов внутри 70-часового блока. Если магазин понадобится раньше — собери демо-магазин по документации: товары, варианты, корзина, доставка, оплата. Шаг не заменяет разделы 5–7, а даёт взять заказ до них.',
    hours: 10,
    value: 60,
    optional: true,
    url: 'https://developer.wordpress.org/block-editor/getting-started/',
  },
  {
    id: 'a-elementor',
    track: 'A',
    kind: 'practice',
    title: 'Один сайт на Elementor от макета до сдачи',
    meta: 'практика на своём WordPress',
    note: 'У Сокирки Elementor только кусочком про виджеты, а в парсере он встречается регулярно: клиенты приходят с готовым сайтом на Elementor и просят доработать. Отдельный курс не нужен — собери один сайт целиком: шаблон, шапка и подвал через Theme Builder, форма, адаптив, и разбери, как у него устроены секции, чтобы чинить чужие. Готовый сайт — в кейсы.',
    hours: 6,
    value: 75,
  },
  {
    id: 'm-a-wp',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: доработки WordPress по коду',
    note: 'Правки тем и плагинов, хуки, интеграции — самая частая категория заказов на Kwork и FL.ru.',
    hours: 0,
  },
  {
    id: 'a-sochirca-2',
    track: 'A',
    kind: 'course',
    title: 'Весь WordPress и PHP, разделы 5–7',
    meta: 'Сокирка',
    note: 'Посадка HTML-шаблона на WP (15 ч), интернет-магазин на WooCommerce (12 ч), виджеты для Elementor (8 ч). Разделы 8–10 (WPBakery, SiteOrigin, Beaver) — мимо, 11–12 (155 ч практики) — как справочник под конкретный заказ.',
    hours: 70,
    value: 80,
    video: 35,
    factor: 2,
    url: 'https://www.udemy.com/course/all-wordpress/',
  },
  {
    id: 'm-a-shop',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: магазины на WooCommerce 15–65 тыс. ₽ и онлайн-школы на WP 20–55 тыс. ₽',
    note: 'Уже по твоему прайсу, а не по нижней планке.',
    hours: 0,
  },
  {
    id: 'a-kudlai-base',
    track: 'A',
    kind: 'course',
    title: 'PHP 8. От теории к практике',
    meta: 'Кудлай · справочник',
    note: 'Держи открытым рядом с первым разделом Сокирки и смотри только непонятное. Целиком (21 ч) — только если база PHP у Сокирки покажется слишком быстрой.',
    hours: 10,
    value: 30,
    video: 5,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/php-8-ua/',
  },
  {
    id: 'a-schiff',
    track: 'A',
    kind: 'course',
    title: 'Become a WordPress Developer',
    meta: 'Brad Schiff · EN · выборочно',
    note: 'Разделы 13–16 (REST API, AJAX), 18–19 (роли пользователей, пользовательский контент), 21 (деплой), 24 (Gutenberg-блоки на React). Это личные кабинеты для онлайн-школ на WP. Остальные 34 ч дублируют Сокирку.',
    hours: 24,
    value: 45,
    video: 12,
    factor: 2,
    url: 'https://www.udemy.com/course/become-a-wordpress-developer-php-javascript/',
  },
  {
    id: 'a-acf',
    track: 'A',
    kind: 'course',
    title: 'WordPress Theme Development with ACF',
    meta: 'Riani · EN',
    note: 'ACF постоянно встречается в кастомных сайтах для клиентов. Его же курс по Elementor для Themeforest — мимо: это про продажу тем на маркетплейсе.',
    hours: 16,
    value: 35,
    video: 11,
    factor: 1.5,
    optional: true,
    url: 'https://www.udemy.com/course/wordpress-advanced-theme-development-with-acf-acf-pro/',
  },
  {
    id: 'a-ai',
    track: 'A',
    kind: 'course',
    title: 'AI-разработка и создание AI-агентов',
    meta: 'Фокеев',
    note: 'Claude, основы LLM, агенты, ассистент в Telegram, сервисы автоматизации. Напрямую закрывает «AI-боты» в услугах — спрос есть, конкуренции меньше, чем в вёрстке.',
    hours: 10,
    value: 70,
    video: 6.3,
    factor: 1.5,
    url: 'https://www.udemy.com/course/ai-ai-cph/',
  },
  {
    id: 'm-a-ai',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: чат-боты на нейросетях для сайта и Telegram',
    note: 'Под «дополнительные услуги» с сайта: интеграции, AI-боты, сопровождение.',
    hours: 0,
  },
  {
    id: 'a-bitrix',
    track: 'A',
    kind: 'free',
    title: '1С-Битрикс для разработчиков',
    meta: 'dev.1c-bitrix.ru/learning · academy.1c-bitrix.ru',
    note: 'Официальные бесплатные курсы: сначала «Разработчик», потом «Администратор» выборочно. Для практики — пробная версия «Управление сайтом». 40 ч — оценка, поправь по факту.',
    hours: 40,
    value: 75,
    url: 'https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43',
  },
  {
    id: 'm-a-bitrix',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: доработки и интеграции на Битриксе',
    note: 'Дорогие заказы русского рынка и мало исполнителей. Работает удалённо и после переезда.',
    hours: 0,
  },
  {
    id: 'a-getcourse',
    track: 'A',
    kind: 'free',
    title: 'GetCourse: администраторская часть',
    meta: 'Университет GetCourse · «Администратор GetCourse от А до Я»',
    note: 'Онлайн-школы на GetCourse заявлены на сайте, но курса в библиотеке нет. Проходи, когда придёт первый такой заказ — или заранее, если парсер показывает спрос. 15 ч — оценка.',
    hours: 15,
    value: 25,
    optional: true,
    url: 'https://getcourse.ru/course/admin',
  },
  {
    id: 'a-shopify-1',
    track: 'A',
    kind: 'course',
    title: 'Complete Shopify Course 2026, разделы 2–5',
    meta: 'M C, Dennis C · EN',
    note: 'Настройка и кастомизация магазина, настройки, выполнение заказов. Дропшиппинг, print-on-demand и реклама (разделы 9–15) — для владельцев магазинов, не для разработчика.',
    hours: 6,
    value: 15,
    video: 5,
    factor: 1.2,
    optional: true,
    url: 'https://www.udemy.com/course/ultimate-shopify-course-beginner-to-shopify-expert-2024/',
  },
  {
    id: 'm-a-shopify',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: Shopify для зарубежных клиентов',
    note: 'Открывается англоязычный рынок — Upwork и подобные.',
    hours: 0,
  },
  {
    id: 'a-ux',
    track: 'A',
    kind: 'course',
    title: 'UX-веб-дизайн в Figma с нейросетями',
    meta: 'Фокеев',
    note: 'Самый полезный из оставшихся дизайн-курсов: аргументированный редизайн для бизнес-клиентов — услуга «редизайн» с сайта. Figma Pro, Motion-дизайн, Photoshop, Illustrator — только если решишь продавать дизайн отдельно.',
    hours: 19,
    value: 25,
    video: 12.7,
    factor: 1.5,
    optional: true,
    url: 'https://www.udemy.com/course/ux-design-foundation/',
  },
  {
    id: 'a-multilink',
    track: 'A',
    kind: 'course',
    title: 'Мультиссылки и мини-сайты для Instagram',
    meta: 'SendPulse · 44 мин',
    note: 'Глянь за вечер, если по парсеру такие заказы попадаются, иначе пропускай.',
    hours: 1,
    value: 20,
    video: 0.7,
    optional: true,
    url: 'https://www.udemy.com/course/multilink-for-instagram/',
  },

  {
    id: 'a-kudlai-oop',
    track: 'A',
    kind: 'course',
    title: 'PHP 8. ООП. Собственный MVC-фреймворк',
    meta: 'Кудлай',
    note: 'Фреймворк (16 ч): автозагрузка, роутинг, валидация, БД, авторизация, middleware, кеш. Потом CMS на нём (11 ч). Мост к Битриксу и к серьёзным плагинам WordPress. PHP после Сокирки ещё свежий — не откладывай.',
    hours: 54,
    value: 35,
    video: 26.8,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/php-8-framework/',
  },
  {
    id: 'a-shopify-2',
    track: 'A',
    kind: 'course',
    title: 'The Complete Shopify Theme Development Course',
    meta: 'Rajinder Pal · EN',
    note: 'Shopify CLI, Liquid, секции темы, Alpine JS. Именно это продаётся как «разработка темы Shopify» на Upwork. В РФ Shopify почти не работает — это рынок зарубежных клиентов, важный с переездом.',
    hours: 32,
    value: 10,
    video: 15.8,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/the-complete-shopify-theme-development-course/',
  },
  // ───────────────────────── Трек B — fullstack ─────────────────────────
  {
    id: 'b-stepik-js-full',
    track: 'B',
    kind: 'course',
    title: 'Полный курс по JavaScript — с нуля до результата',
    meta: 'Фокеев · Stepik · 223 из 224 шагов',
    note: 'Закрыт. База JavaScript есть: синтаксис, DOM, события, асинхронность на уровне курса. Дальше идёт углубление, а не повторение.',
    hours: 0,
    value: 90,
    done: true,
    url: 'https://stepik.org/course/130424',
  },
  {
    id: 'b-stepik-tvoy-js',
    track: 'B',
    kind: 'course',
    title: 'Твой JavaScript',
    meta: 'Тарасов · Stepik · 258 из 265 шагов',
    note: 'Задачный курс, закрыт на 97 %. Оставшиеся семь шагов — на один вечер.',
    hours: 0,
    value: 80,
    done: true,
    url: 'https://stepik.org/course/210361',
  },
  {
    id: 'b-stepik-react-full',
    track: 'B',
    kind: 'course',
    title: 'Полный курс по React JS — Redux, Router, Tailwind CSS',
    meta: 'Фокеев · Stepik · 334 из 334 шагов',
    note: 'Закрыт полностью. Основы React, Redux и роутинга есть, поэтому «React до middle» ниже — про паттерны и серверное состояние, а не про хуки с нуля.',
    hours: 0,
    value: 95,
    done: true,
    url: 'https://stepik.org/course/221235',
  },
  {
    id: 'b-js',
    track: 'B',
    kind: 'free',
    title: 'JavaScript вглубь',
    meta: 'learn.javascript.ru',
    note: 'Разделы «Продвинутая работа с функциями» и «Асинхронность»: замыкания, промисы, Event Loop, микро- и макрозадачи. Первый пункт чек-листа DeepSeek — без этого не пишется серверный код.',
    hours: 15,
    value: 90,
    url: 'https://learn.javascript.ru/advanced-functions',
  },
  {
    id: 'b-stepik-oop',
    track: 'B',
    kind: 'free',
    title: 'Миникурс: основы ООП для JS/TS и React-разработчика',
    meta: 'Stepik · 140 шагов',
    note: 'Классы, наследование, интерфейсы на языке фронтендера. Два вечера перед TypeScript — иначе generics и абстракции у Непомнящего пойдут тяжело.',
    hours: 3,
    value: 60,
    units: 140,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/245362',
  },
  {
    id: 'b-stepik-ts',
    track: 'B',
    kind: 'course',
    title: 'TypeScript для профессиональной разработки',
    meta: 'Непомнящий · Stepik · 232 шага',
    note: 'Куплен, пройдено 15 шагов. Основной курс по TypeScript вместо чтения handbook с нуля: типы, generics, narrowing, utility-типы, tsconfig на практике. Бесплатный «Программирование на TypeScript» Смирнова с первого аккаунта — дубль, не трать на него время.',
    hours: 14,
    value: 95,
    units: 232,
    unitWord: 'шагов',
    unitsDone: 15,
    url: 'https://stepik.org/course/121859',
  },
  {
    id: 'b-git',
    track: 'B',
    kind: 'free',
    title: 'Git по-взрослому: ветки, rebase, конфликты, pull request',
    meta: 'Pro Git, главы 3 и 7 · learngitbranching.js.org',
    note: 'Пользуешься каждый день, но на собеседовании спросят про ветвление, rebase против merge, разрешение конфликтов и flow с pull request — и это заметный пробел. Вечер на главы про ветки и инструменты Pro Git, час на интерактивный тренажёр, потом пет-проект ведёшь только через ветки и PR, даже в одиночку.',
    hours: 4,
    value: 80,
    url: 'https://git-scm.com/book/ru/v2',
  },
  {
    id: 'b-ts',
    track: 'B',
    kind: 'free',
    title: 'TypeScript — документация и handbook',
    note: 'Справочник к курсу Непомнящего: narrowing, utility-типы, tsconfig — читать по мере вопросов, а не подряд.',
    hours: 10,
    value: 40,
    optional: true,
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
  },
  {
    id: 'b-stepik-js-pro',
    track: 'B',
    kind: 'course',
    title: 'Самый полный курс по JavaScript для опытных программистов',
    meta: 'Stepik · 1141 шаг · пройдено 27 %',
    note: 'Куплен и пройден на четверть — не бросай, но и не ставь впереди Node. По желанию, по вечерам: замыкания, прототипы, асинхронность на глубину собеседования. «Твой JavaScript PRO» с того же аккаунта — дубль по темам, его в архив.',
    hours: 52,
    value: 45,
    optional: true,
    units: 1141,
    unitWord: 'шагов',
    unitsDone: 314,
    url: 'https://stepik.org/course/177315',
  },
  {
    id: 'b-node',
    track: 'B',
    kind: 'course',
    title: 'Node.js — полный курс',
    meta: 'Стащук · обновлён 03/2026',
    note: 'Архитектура Node, цикл событий, модули, fs/path/http/stream, Express и API. Раздел 3 «Краткий курс по JavaScript» пропускай — это твоя база. Express руками до Next.js, как советовал Google AI.',
    hours: 35,
    value: 90,
    video: 17.7,
    factor: 2,
    url: 'https://www.udemy.com/course/nodejs-ru/',
  },
  {
    id: 'b-sql',
    track: 'B',
    kind: 'free',
    title: 'SQL и PostgreSQL — основы',
    meta: 'Тренажёр ДВФУ · Stepik · 206 задач',
    note: 'Оба чек-листа ставят PostgreSQL в обязательный минимум. Интерактивный тренажёр ДВФУ — задачи без воды, на втором аккаунте уже 42 из 206. SELECT / JOIN / INSERT, связь users → orders, индексы на пальцах. «SQL для начинающих» (платный, 33 из 460) — справочник, «Введение в SQL» — дубль, в архив.',
    hours: 12,
    value: 90,
    units: 206,
    unitWord: 'задач',
    unitsDone: 42,
    url: 'https://stepik.org/course/63054',
  },
  {
    id: 'b-stepik-docker',
    track: 'B',
    kind: 'free',
    title: 'Docker для начинающих + практический опыт',
    meta: 'Stepik · 128 шагов',
    note: 'Бесплатное введение перед курсом Кочергина, по желанию: образы, контейнеры, тома. «Знакомство с Docker» с первого аккаунта короче и целиком внутри этого.',
    hours: 5,
    value: 35,
    optional: true,
    units: 128,
    unitWord: 'шагов',
    unitsDone: 1,
    url: 'https://stepik.org/course/123300',
  },
  {
    id: 'b-docker',
    track: 'B',
    kind: 'course',
    title: 'Docker и Docker Compose — деплой проекта с нуля',
    meta: 'Кочергин',
    note: 'Dockerfile, API + база + фронт в Compose, nginx, сети, деплой на сервер. Сразу после курса упакуй в Docker свой парсер — следующим шагом он и поедет на сервер.',
    hours: 8,
    value: 85,
    video: 3.7,
    factor: 2,
    url: 'https://www.udemy.com/course/docker-and-docker-compose/',
  },
  {
    id: 'b-pet-mvp',
    track: 'B',
    kind: 'practice',
    title: 'Пет-проект, рабочий минимум: парсер заказов на сервере',
    meta: 'Node · PostgreSQL · Docker · Telegram',
    note: 'Не жди конца трека. Node и SQL сейчас свежие — собери на них работающий минимум: парсер бирж по расписанию, таблицы в PostgreSQL, отдача через API, уведомления в Telegram, всё в Docker на VPS. Дальше каждый следующий шаг трека ложится в этот же проект, а не в новую учебную папку: выучил тесты — покрыл его тестами, выучил Next.js — сделал ему панель. Так материал закрепляется, и к концу выходит один живой продукт вместо десяти клонов из курсов.',
    hours: 30,
    value: 100,
  },
  {
    id: 'm-b-deploy',
    track: 'B',
    kind: 'milestone',
    title: 'Умеешь поднять проект на VPS в Docker с nginx и SSL',
    note: 'Блок DevOps из чек-листа закрыт на уровне «сам разворачиваю то, что написал».',
    hours: 0,
  },
  {
    id: 'b-larichev',
    track: 'B',
    kind: 'course',
    title: 'Node.js — с нуля, основы и архитектура приложений',
    meta: 'Ларичев',
    note: 'Express, переход на TypeScript, DI (InversifyJS), Prisma поверх SQL, JWT, unit- и e2e-тесты. Единственный курс в наборе про TypeScript и архитектуру на бэкенде — проходи целиком.',
    hours: 36,
    value: 55,
    video: 18.1,
    factor: 2,
    url: 'https://www.udemy.com/course/nodejs-start/',
  },
  {
    id: 'b-tissen',
    track: 'B',
    kind: 'course',
    title: 'Fullstack: React + Node.js/Express — два проекта',
    meta: 'Тиссен',
    note: 'Два проекта целиком, фронт и бэк вместе. Здесь React встречается с твоим новым бэкендом: контроллеры, авторизация, связь по API.',
    hours: 48,
    value: 85,
    video: 24.1,
    factor: 2,
    url: 'https://www.udemy.com/course/fullstack-react-nodejsexpress/',
  },
  {
    id: 'm-b-api',
    track: 'B',
    kind: 'milestone',
    title: 'Свой API + React-фронт: можно брать интеграции и личные кабинеты на Node',
    note: 'Первые fullstack-заказы под «дополнительные услуги» с сайта.',
    hours: 0,
  },
  {
    id: 'b-mongo',
    track: 'B',
    kind: 'course',
    title: 'MongoDB — полный курс',
    meta: 'Стащук',
    note: 'После PostgreSQL, не вместо: Google AI прямо советует начинать с реляционной базы. Mongo нужна, потому что на ней держатся MERN-проекты и половина курсов по Node.',
    hours: 13,
    value: 40,
    video: 8.7,
    factor: 1.5,
    optional: true,
    url: 'https://www.udemy.com/course/mongodb-ru/',
  },
  {
    id: 'b-socketio',
    track: 'B',
    kind: 'course',
    title: 'SocketIO and TypeScript',
    meta: 'Bradley · EN',
    note: 'WebSockets из чек-листа DeepSeek плюс редкая вещь: деплой руками на VPS — nginx, домен, SSL. Тот самый «Linux, SSH, nginx, логи».',
    hours: 5,
    value: 45,
    video: 2.9,
    factor: 1.5,
    url: 'https://www.udemy.com/course/typescript-socketio/',
  },
  {
    id: 'b-next-wp',
    track: 'B',
    kind: 'course',
    title: 'Next JS & WordPress: headless-сайты',
    meta: 'Phillips · EN · обновлён 07/2026',
    note: 'Next.js (pages router + раздел про переход на App Router), GraphQL, headless WordPress с ACF, Tailwind, деплой на Vercel. Связывает WordPress из трека A с fullstack.',
    hours: 17,
    value: 60,
    video: 8.4,
    factor: 2,
    url: 'https://www.udemy.com/course/next-js-wordpress/',
  },
  {
    id: 'b-nextpizza',
    track: 'B',
    kind: 'free',
    title: 'NextPizza',
    meta: 'Archakov Blog · YouTube',
    note: 'Next.js App Router, TypeScript, Prisma, PostgreSQL, авторизация, корзина, оплата — курс из рекомендаций Google AI. Сюда приходишь уже с Express и SQL в руках, поэтому Server Actions не выглядят магией. 40 ч — оценка, длину плейлиста проверь.',
    hours: 40,
    value: 70,
    optional: true,
    url: 'https://www.youtube.com/watch?v=GUwizGbY4cc',
  },
  {
    id: 'b-cicd',
    track: 'B',
    kind: 'free',
    title: 'GitHub Actions — CI/CD для своего проекта',
    note: 'Линт + тесты + сборка Docker-образа на push. Хватит документации GitHub и одного вечера. Этот сайт, кстати, деплоится через такой же workflow.',
    hours: 5,
    value: 75,
    url: 'https://docs.github.com/ru/actions',
  },
  {
    id: 'b-react-mid',
    track: 'B',
    kind: 'free',
    title: 'React до middle',
    meta: 'документация Redux Toolkit, react.dev',
    note: 'Redux Toolkit + RTK Query, memo / useMemo / useCallback, кастомные хуки, виртуализация списков. Не отдельный курс, а требования к коду пет-проекта — читаешь и сразу применяешь.',
    hours: 10,
    value: 90,
    url: 'https://redux-toolkit.js.org/',
  },
  {
    id: 'b-stepik-react-pro',
    track: 'B',
    kind: 'course',
    title: 'React для современных веб-приложений',
    meta: 'Непомнящий · Stepik · 201 шаг',
    note: 'Куплен, 6 шагов пройдено. Второй заход в React после курса Фокеева — уже на уровне требований вакансий: композиция, производительность, работа с сервером. Проходить рядом с пет-проектом и сразу переносить в его код.',
    hours: 13,
    value: 80,
    units: 201,
    unitWord: 'шагов',
    unitsDone: 6,
    url: 'https://stepik.org/course/114197',
  },
  {
    id: 'b-stepik-redux',
    track: 'B',
    kind: 'course',
    title: 'Redux для управления состоянием React-приложений',
    meta: 'Непомнящий · Stepik · 224 шага',
    note: 'По желанию: Redux уже был у Фокеева, а для пет-проекта хватит RTK Query из «React до middle». Куплен — вернись, если на собеседовании начнут спрашивать middleware и нормализацию стора.',
    hours: 11,
    value: 30,
    optional: true,
    units: 224,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/113714',
  },
  {
    id: 'b-testing',
    track: 'B',
    kind: 'free',
    title: 'Тестирование React: Jest + React Testing Library',
    meta: 'testing-library.com · jestjs.io',
    note: 'Единственная дыра стека относительно React-вакансий: в библиотеке нет ни одного курса по тестам. Цель — покрыть пет-проект: unit-тесты утилит, тесты компонентов через RTL, один интеграционный на ключевой сценарий, запуск в GitHub Actions.',
    hours: 8,
    value: 95,
    url: 'https://testing-library.com/docs/react-testing-library/intro/',
  },
  {
    id: 'b-perf',
    track: 'B',
    kind: 'free',
    title: 'Производительность React: профилировщик, code splitting, Core Web Vitals',
    meta: 'react.dev · DevTools Performance · Lighthouse',
    note: 'Курса не нужно — замеры на своём пет-проекте: React Profiler и вкладка Performance, мемоизация только там, где профилировщик показал лишние перерисовки, lazy и code splitting по маршрутам, картинки и шрифты, Lighthouse не ниже 90 по всем четырём метрикам. Цифры «до и после» — в README: это отдельный аргумент на собеседовании.',
    hours: 8,
    value: 70,
    url: 'https://react.dev/reference/react/Profiler',
  },
  {
    id: 'b-pet',
    track: 'B',
    kind: 'practice',
    title: 'Пет-проект, доводка до продукта: панель, тесты, CI',
    meta: 'Next.js App Router · Prisma · GitHub Actions',
    note: 'Вторая половина того же парсера, а не новый проект. Панель на Next.js App Router с фильтрами по стеку, серверное состояние через RTK Query или TanStack Query, тесты и линт в CI, логи и алерты, README про архитектуру и живое демо по ссылке. Критерий приёмки один: TypeScript в режиме strict без единого any и публичный репозиторий, который не стыдно дать на собеседовании. Вариант Б для iGaming — карточная игра «21» на React + PixiJS/GSAP и Node + Socket.IO.',
    hours: 70,
    value: 100,
  },
  {
    id: 'm-b-portfolio',
    track: 'B',
    kind: 'milestone',
    title: 'Живой проект на Next.js + Node + PostgreSQL + Docker с публичным репозиторием',
    note: 'Главная строчка в резюме fullstack-джуна и главный кейс на verno-dev.com. Можно откликаться на удалёнку.',
    hours: 0,
  },
  {
    id: 'b-stepik-interview',
    track: 'B',
    kind: 'free',
    title: 'Проверка знаний и подготовка к собеседованию по JavaScript',
    meta: 'Stepik · 315 задач',
    note: 'Лучший бесплатный тренажёр под интервью, лежит на обоих аккаунтах нетронутым. После пет-проекта: по 20–30 задач в день перед откликами на вакансии, слабые темы — обратно в «JavaScript вглубь».',
    hours: 6,
    value: 85,
    units: 315,
    unitWord: 'задач',
    unitsDone: 1,
    url: 'https://stepik.org/course/189305',
  },
  {
    id: 'b-mock-interviews',
    track: 'B',
    kind: 'practice',
    title: 'Пробные собеседования: три-пять моков',
    meta: 'getmentor.dev · Solvery · pramp',
    note: 'Тренажёр проверяет теорию, моки — умение объяснять решения вслух. Три-пять интервью с практикующими разработчиками: бесплатные менторы на getmentor.dev, платные на Solvery, peer-to-peer на pramp (на английском). После каждого — список пробелов, и только потом отклики на вакансии.',
    hours: 6,
    value: 80,
    url: 'https://getmentor.dev/',
  },
  {
    id: 'b-nest',
    track: 'B',
    kind: 'free',
    title: 'NestJS: «Облачное хранилище»',
    meta: 'Archakov Blog · Next.js + NestJS + TypeScript',
    note: 'Оба чек-листа говорят «отложить NestJS» — сюда приходишь после пет-проекта. 40 ч — оценка.',
    hours: 40,
    value: 35,
    optional: true,
    url: 'https://www.youtube.com/watch?v=_oR1p79t6gw',
  },
  {
    id: 'b-hardening',
    track: 'B',
    kind: 'free',
    title: 'Безопасность, логирование, основы system design',
    meta: 'OWASP Top 10 · Winston/Pino · Sentry',
    note: 'Из «дополнительных слоёв» DeepSeek: CSRF/XSS/SQL-инъекции, rate limiting, CORS, структурные логи через Pino и алерты в Sentry. Не по желанию: на middle-собеседовании спрашивают, как ты узнаёшь о падении в проде. Читаешь и добавляешь в пет-проект — так это и запоминается.',
    hours: 10,
    value: 65,
    url: 'https://owasp.org/www-project-top-ten/',
  },
  {
    id: 'b-pixi',
    track: 'B',
    kind: 'free',
    title: 'PixiJS + GSAP',
    meta: 'если iGaming всерьёз',
    note: 'Специализация из чек-листа DeepSeek: 2D-рендеринг, анимации, канвас. Берётся вместе с вариантом Б пет-проекта (карточная игра). 30 ч — оценка.',
    hours: 30,
    value: 15,
    optional: true,
    url: 'https://pixijs.com/8.x/guides/getting-started/intro',
  },
  {
    id: 'b-rn',
    track: 'B',
    kind: 'course',
    title: 'React Native 2026 + React Native: Advanced Concepts',
    meta: 'Sawy, Grider · EN · 41 ч видео',
    note: 'Только если мобильная разработка станет целью. Курс Grider старый — проверь дату обновления, прежде чем тратить время.',
    hours: 80,
    value: 20,
    video: 41,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/the-best-react-native-course/',
  },
]

export const HABITS: Habit[] = [
  { track: 'A', time: '1 ч/день', text: 'Биржи: отклики по сводке парсера, переписка, оценка задач' },
  { track: 'A', time: 'каждый заказ', text: 'Кейс на verno-dev.com и отзыв на бирже — портфолио продаёт лучше курсов' },
  { track: 'A', time: '1 раз/нед', text: 'Свериться с парсером: какой стек реально заказывают — и переставить курсы, если картина другая' },
  { track: 'A', time: 'пока нет первых денег', text: 'Держать 70 % времени на треке A и 30 % на B — иначе оба идут и ни один не заканчивается' },
  { track: 'B', time: '20–30 мин/день', text: 'Codewars 6–7 kyu, позже LeetCode easy — алгоритмы для собеседований' },
  { track: 'B', time: '30 мин/день', text: 'Английский до B2: документация и видео по теме в оригинале, англоязычные курсы без субтитров' },
  { track: 'B', time: 'всегда', text: 'Читать документацию в первоисточнике, а не пересказы' },
]

import remindersJson from './reminders.json'

export interface Reminder {
  id: string
  /** ISO-дата разового напоминания (наступает с этой даты) */
  date?: string
  /** Повторяющееся: weekly — по дню недели, monthly — по числу месяца */
  repeat?: 'weekly' | 'monthly'
  /** День недели для weekly: 1 = понедельник … 7 = воскресенье */
  weekday?: number
  /** Число месяца для monthly: 1–28 */
  day?: number
  title: string
  text?: string
  link?: { hash: string; label: string }
}

/** Общие напоминания живут в reminders.json — его же читает workflow телеграм-бота */
export const REMINDERS: Reminder[] = remindersJson as Reminder[]

export interface Skipped {
  track: TrackId
  title: string
  meta: string
  /** Почему пропущен */
  why: string
  /** Стоит ли вернуться, 0–100: не «хороший ли курс», а вероятность, что он реально понадобится за ближайшие два года */
  returnValue: number
  /** Что с ним делать: never — не возвращаться; on-demand — открыть под конкретный заказ; later — после определённого шага плана */
  action: 'never' | 'on-demand' | 'later'
  /** Условие возврата одной фразой */
  trigger: string
  /** Ссылка на курс, если есть */
  url?: string
}

/** Всё, что есть в библиотеке и не стало шагом плана: остатки Udemy и оба аккаунта Stepik */
export const SKIPPED: Skipped[] = [
  {
    track: 'A',
    title: 'Весь WordPress и PHP, разделы 8–12',
    meta: 'Сокирка · 172 ч',
    why: 'справочник под конкретный заказ',
    returnValue: 55,
    action: 'on-demand',
    trigger: 'когда заказ упрётся в тему, которой нет в разделах 1–7',
  },
  {
    track: 'A',
    title: 'WordPress Development 2026',
    meta: 'Madani · 14,5 ч',
    why: 'дубль Сокирки и Schiff; headless-часть — при заказе',
    returnValue: 45,
    action: 'on-demand',
    trigger: 'если придёт заказ на headless: WordPress как админка, фронт на Next.js',
  },
  {
    track: 'A',
    title: 'Веб-дизайн в Figma — продвинутый',
    meta: 'дизайн-блок Udemy, 55 ч на пять курсов',
    why: 'основ из a-figma хватает, чтобы читать макеты и рисовать простые лендинги',
    returnValue: 40,
    action: 'later',
    trigger: 'после a-figma, если на реальных заказах упрёшься в потолок',
  },
  {
    track: 'A',
    title: 'PHP 8. От теории к практике, остаток',
    meta: 'Кудлай · 16 ч',
    why: 'если база Сокирки окажется быстрой',
    returnValue: 35,
    action: 'later',
    trigger: 'после a-sochirca-1, если PHP у Сокирки пойдёт слишком бегло',
  },
  {
    track: 'A',
    title: 'Become a WordPress Developer, остальные разделы',
    meta: 'Schiff · 34 ч',
    why: 'дубль',
    returnValue: 30,
    action: 'on-demand',
    trigger: 'если по заказу нужен разбор темы, которой у Сокирки нет',
  },
  {
    track: 'A',
    title: 'WordPress Theme Development for Themeforest with Elementor',
    meta: 'Riani · 21,4 ч',
    why: 'продажа тем на маркетплейсе, не фриланс',
    returnValue: 20,
    action: 'never',
    trigger: 'никогда — продажа шаблонов это отдельный бизнес со своим циклом',
  },
  {
    track: 'A',
    title: 'Illustrator',
    meta: 'дизайн-блок Udemy, 55 ч на пять курсов',
    why: 'логотипы и фирменный стиль — другая профессия',
    returnValue: 15,
    action: 'never',
    trigger: 'только если решишь продавать фирменный стиль отдельной услугой',
  },
  {
    track: 'A',
    title: 'Motion-дизайн',
    meta: 'дизайн-блок Udemy, 55 ч на пять курсов',
    why: 'анимация на сайтах делается кодом: CSS и GSAP',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
  },
  {
    track: 'A',
    title: 'Photoshop, два курса',
    meta: 'дизайн-блок Udemy, 55 ч на пять курсов',
    why: 'Figma закрыла всё, что нужно вебу; сжатие картинок — Squoosh или TinyPNG',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
  },
  {
    track: 'A',
    title: 'Complete Shopify Course, разделы 9–15',
    meta: '10 ч',
    why: 'дропшиппинг и реклама — для владельцев магазинов',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда — это для владельца магазина, не для разработчика',
  },
  {
    track: 'A',
    title: 'Как заработать на фрилансе, конструктор сайтов Таптоп',
    meta: 'Stepik · 3 ч · бесплатно',
    why: 'русский конструктор, в сводках парсера пока редок',
    returnValue: 25,
    action: 'on-demand',
    trigger: 'если в парсере начнут попадаться заказы на Таптоп — вечер, и можно брать',
    url: 'https://stepik.org/course/203658',
  },
  {
    track: 'A',
    title: 'Интерактивный тренажёр: HTML, CSS, JavaScript',
    meta: 'Stepik · 30 ч · бесплатно',
    why: 'вёрстка уже закрыта двумя курсами Фокеева; тренажёр для тех, кто с нуля',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/114064',
  },
  {
    track: 'A',
    title: 'Компетенция Верстальщик — HTML, CSS, JavaScript',
    meta: 'Stepik · 28 ч · куплен',
    why: 'дубль закрытой вёрстки',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/120081',
  },
  {
    track: 'A',
    title: 'Лучший в IT. Как работает интернет + фронтенд',
    meta: 'Stepik · 15 ч · бесплатно',
    why: 'вводный обзор для нулевых, ты дальше этого',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/257879',
  },
  {
    track: 'A',
    title: '30 элементов сайта на примере Materialize CSS',
    meta: 'Stepik · 5 ч · бесплатно',
    why: 'Materialize давно не в ходу, элементы делаются на чистом CSS',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/132471',
  },
  {
    track: 'A',
    title: 'Тренажёр по вёрстке, плагин Emmet',
    meta: 'Stepik · 4 ч · бесплатно',
    why: 'Emmet осваивается за час по шпаргалке',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/113654',
  },
  {
    track: 'A',
    title: 'HTML CSS (mini)',
    meta: 'Stepik · 5 ч · бесплатно',
    why: 'дубль закрытой вёрстки',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/187918',
  },
  {
    track: 'A',
    title: 'CSS Flexbox — полный курс и практика',
    meta: 'Stepik · 2 ч · бесплатно · на обоих аккаунтах',
    why: 'Flexbox был и у Фокеева, и в Grid-разделах Webflow',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/122593',
  },
  {
    track: 'A',
    title: 'Профессия веб верстальщик — пакет из 2 курсов',
    meta: 'Stepik · 38 ч · куплен',
    why: 'обёртка над двумя курсами вёрстки, которые уже пройдены',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/121498',
  },
  {
    track: 'A',
    title: 'Свой сайт в интернете. WordPress и базы данных — это просто!',
    meta: 'Stepik · бесплатно',
    why: 'дубль пройденного WordPress без кода',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/201247',
  },
  {
    track: 'A',
    title: 'OpenCart',
    meta: 'курса нет — документация и чужой код',
    why: 'своей ниши почти не осталось: новые магазины в РФ идут на WooCommerce, Tilda, Insales и маркетплейсы, а OpenCart держится на поддержке старых сайтов',
    returnValue: 25,
    action: 'on-demand',
    trigger: 'если придёт заказ на доработку готового сайта на OpenCart — там всё равно читать чужой код, а не курс',
  },
  {
    track: 'B',
    title: 'Инструменты разработчика',
    meta: 'Непомнящий · Stepik · 11 ч · куплен',
    why: 'терминал, npm, сборка, Git — то, что обычно учат по ходу; отдельного шага в плане нет',
    returnValue: 40,
    action: 'later',
    trigger: 'после b-git, если чтения Pro Git окажется мало и захочется системно',
    url: 'https://stepik.org/course/114174',
  },
  {
    track: 'B',
    title: 'SQL для начинающих',
    meta: 'IT Guru · Stepik · 9 ч · куплен · 33 из 460',
    why: 'основной шаг по SQL — тренажёр ДВФУ; этот оставлен справочником',
    returnValue: 35,
    action: 'on-demand',
    trigger: 'когда в тренажёре встретится тема, которую хочется прочитать, а не решать',
    url: 'https://stepik.org/course/133728',
  },
  {
    track: 'B',
    title: 'Тесты и задачи по HTML, CSS и JavaScript',
    meta: 'Stepik · 4 ч · бесплатно',
    why: 'вопросы уровня фронтенд-собеседования, отдельно от плана',
    returnValue: 30,
    action: 'on-demand',
    trigger: 'за неделю до первого собеседования на фронт — прогнать за вечер',
    url: 'https://stepik.org/course/182715',
  },
  {
    track: 'B',
    title: 'Твой JavaScript PRO',
    meta: 'Тарасов · Stepik · 83 ч · куплен · 178 из 771',
    why: 'дубль по темам с «Самым полным курсом по JS», который уже в плане по желанию',
    returnValue: 25,
    action: 'later',
    trigger: 'после b-stepik-js-pro, если нужны ещё задачи, — и не раньше пет-проекта',
    url: 'https://stepik.org/course/247486',
  },
  {
    track: 'B',
    title: 'React.JS — курс для повторения',
    meta: 'Stepik · 2 ч · бесплатно',
    why: 'короткий повтор, полезен только перед собеседованием',
    returnValue: 20,
    action: 'on-demand',
    trigger: 'за пару дней до собеседования по React — освежить за вечер',
    url: 'https://stepik.org/course/251035',
  },
  {
    track: 'B',
    title: 'Профессия Frontend-разработчик',
    meta: 'Stepik · 99 ч · куплен',
    why: 'обёртка над курсами Непомнящего, которые в плане стоят по отдельности',
    returnValue: 20,
    action: 'never',
    trigger: 'никогда — всё нужное из него уже разобрано на шаги',
    url: 'https://stepik.org/course/180789',
  },
  {
    track: 'B',
    title: 'Фундаментальный JavaScript',
    meta: 'Непомнящий · Stepik · 22 ч · куплен',
    why: 'JavaScript закрыт двумя курсами и «вглубь» по learn.javascript.ru',
    returnValue: 15,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/114165',
  },
  {
    track: 'B',
    title: 'Фулстек-разработка веб-сервиса на TypeScript, React, Node.js',
    meta: 'Stepik · бесплатно · 154 шага',
    why: 'обзорный, то же покрывают Ларичев и Тиссен глубже',
    returnValue: 15,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/210768',
  },
  {
    track: 'B',
    title: 'Программирование на TypeScript',
    meta: 'Смирнов · Stepik · 4 ч · бесплатно',
    why: 'дубль курса Непомнящего, который в плане',
    returnValue: 10,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/120959',
  },
  {
    track: 'B',
    title: 'Введение в SQL',
    meta: 'Stepik · 5 ч · бесплатно',
    why: 'третий SQL-курс, дубль тренажёра',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/191774',
  },
  {
    track: 'B',
    title: 'Знакомство с Docker',
    meta: 'Stepik · 1 ч · бесплатно',
    why: 'целиком внутри «Docker для начинающих», который в плане',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/253174',
  },
  {
    track: 'B',
    title: 'Разработка веб-сервисов на Golang',
    meta: 'Stepik · 20 ч · бесплатно',
    why: 'другой язык: Go как второй бэкенд имеет смысл только после уверенного Node',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда в рамках этого плана',
    url: 'https://stepik.org/course/187490',
  },
  {
    track: 'B',
    title: 'Go для чайников!',
    meta: 'Stepik · 15 ч · бесплатно',
    why: 'другой язык',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда в рамках этого плана',
    url: 'https://stepik.org/course/212525',
  },
  {
    track: 'B',
    title: 'Go (Golang) — первое знакомство',
    meta: 'Stepik · 5 ч · бесплатно',
    why: 'другой язык',
    returnValue: 5,
    action: 'never',
    trigger: 'никогда в рамках этого плана',
    url: 'https://stepik.org/course/100208',
  },
  {
    track: 'B',
    title: 'Java. Functional Programming',
    meta: 'Stepik · 23 ч · бесплатно · 140 из 282',
    why: 'другой стек — JS/TS в плане, Java не ведёт ни к заказам, ни к офферу по нему',
    returnValue: 0,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/91497',
  },
  {
    track: 'B',
    title: 'Практический тренажёр по Java',
    meta: 'Stepik · 15 ч · куплен',
    why: 'другой стек',
    returnValue: 0,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/182389',
  },
  {
    track: 'B',
    title: 'Собеседование Java Developer',
    meta: 'Stepik · 9 ч · бесплатно',
    why: 'другой стек',
    returnValue: 0,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/116546',
  },
  {
    track: 'B',
    title: 'Java. Collections Framework',
    meta: 'Stepik · 6 ч · бесплатно',
    why: 'другой стек',
    returnValue: 0,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/1891',
  },
  {
    track: 'B',
    title: 'Java Core: ООП и функциональная парадигма',
    meta: 'Stepik · 4 ч · бесплатно',
    why: 'другой стек',
    returnValue: 0,
    action: 'never',
    trigger: 'никогда',
    url: 'https://stepik.org/course/209683',
  },
]
