export type TrackId = 'A' | 'B'

export type ItemKind = 'course' | 'free' | 'practice' | 'milestone'

export interface Item {
  id: string
  track: TrackId
  kind: ItemKind
  title: string
  /** Инструктор, язык, пометки — выводится серым рядом с названием */
  meta?: string
  /** Что проходить, что пропускать, зачем */
  note: string
  /** Часы работы с практикой (то, что идёт в расписание) */
  hours: number
  /** Чистая длительность видео на Udemy, если есть */
  video?: number
  /** Коэффициент видео → работа, для подписи */
  factor?: number
  /** Необязательный шаг: можно снять галочкой «пропустить» */
  optional?: boolean
  /** Уже пройдено (Tilda) */
  done?: boolean
  /** Ссылка на сам материал: страница курса на Udemy, плейлист на YouTube, документация */
  url?: string
  /** Сколько в материале считаемых единиц — уроков, разделов, видео. Без него прогресс идёт в процентах */
  units?: number
  /** Как называть единицы в подписи «из 123 …» */
  unitWord?: string
  /** Сколько единиц пройдено на момент составления плана; дальше правится вручную и хранится в браузере */
  unitsDone?: number
  /** Польза шага для цели трека, 0–100: не «хороший ли курс», а насколько приближает к заказам или офферу за свои часы */
  value?: number
}

export interface Habit {
  track: TrackId
  time: string
  text: string
}

export interface Track {
  id: TrackId
  name: string
  goal: string
  color: string
}

export const TRACKS: Track[] = [
  {
    id: 'A',
    name: 'Фриланс — деньги как можно быстрее',
    goal: '100 тыс. ₽/мес на русских биржах по стеку verno-dev.com, потом зарубежные клиенты',
    color: 'var(--track-a)',
  },
  {
    id: 'B',
    name: 'Рост как программиста — fullstack',
    goal: 'TypeScript → Node/Express → БД → Docker → Next.js, пет-проект в портфолио, удалёнка за рубежом',
    color: 'var(--track-b)',
  },
]

/** Дата возвращения в вуз — после неё темп падает */
export const UNI_DATE = '2027-02-09'

/** Понедельник, с которого стартует план по умолчанию */
export const DEFAULT_START = '2026-09-07'

export const ITEMS: Item[] = [
  // ───────────────────────── Трек A — фриланс ─────────────────────────
  {
    id: 'a-tilda',
    track: 'A',
    kind: 'course',
    title: 'Создание сайтов и веб-дизайн в Tilda',
    meta: 'Фокеев · 14,5 ч видео · пройдено на 100 %',
    note: 'Лендинги 7–26 тыс. ₽ и бизнес-сайты 12–48 тыс. ₽ по прайсу verno-dev.com можно брать с сегодняшнего дня. Курсы ниже расширяют чек, а не открывают доступ к заказам.',
    hours: 0,
    value: 85,
    video: 14.5,
    done: true,
    url: 'https://www.udemy.com/course/tilda-essential/',
  },
  {
    id: 'a-stepik-wp-nocode',
    track: 'A',
    kind: 'course',
    title: 'Курс по WordPress с нуля до результата — сайты без кода',
    meta: 'Фокеев · Stepik · 90 из 95 шагов',
    note: 'Пройден на 95 %: вместе с Tilda это второй готовый стек под лендинги и бизнес-сайты из прайса. Оставшиеся пять шагов закрой при первом же заказе на WordPress.',
    hours: 0,
    value: 90,
    done: true,
    url: 'https://stepik.org/course/208466',
  },
  {
    id: 'a-stepik-verstka',
    track: 'A',
    kind: 'course',
    title: 'Вёрстка и веб-разработка сайтов — с нуля и продвинутый уровень',
    meta: 'Фокеев · Stepik · два курса, 126 из 137 и 103 из 134 шагов',
    note: 'Оба курса по вёрстке закрыты: HTML, CSS, адаптив и JavaScript для лендингов у тебя есть. Это база и для Webflow, и для WordPress по коду, и для макетов из Figma.',
    hours: 0,
    value: 95,
    done: true,
    url: 'https://stepik.org/course/114109',
  },
  {
    id: 'a-webflow',
    track: 'A',
    kind: 'course',
    title: 'Вёрстка и создание сайтов в Webflow',
    meta: 'Фокеев · 123 урока',
    note: 'Дальше — адаптив, SEO и экспорт проекта. Раздел 13 «Интернет-магазин» можно пропустить: Webflow-магазины в РФ почти не заказывают.',
    hours: 29,
    value: 40,
    video: 19,
    factor: 1.5,
    units: 123,
    unitWord: 'уроков',
    unitsDone: 94,
    url: 'https://www.udemy.com/course/webflow-s/',
  },
  {
    id: 'a-figma',
    track: 'A',
    kind: 'course',
    title: 'Веб-дизайн в Figma — с нуля, основы UX/UI',
    meta: 'Фокеев · выборочно',
    note: '~10 ч из 18: основы, цвет, AutoLayout (разделы 5 и 14), отступы, шрифты, дизайн-система и компоненты, адаптив, прототипирование, экспорт. Нужно, чтобы читать макеты заказчиков и рисовать простые лендинги самому. Картинки, маски, бонус по Photoshop — мимо.',
    hours: 15,
    value: 75,
    video: 10,
    factor: 1.5,
    units: 129,
    unitWord: 'уроков',
    unitsDone: 0,
    url: 'https://www.udemy.com/course/web-figma-ui/',
  },
  {
    id: 'a-theory',
    track: 'A',
    kind: 'course',
    title: 'Теория дизайна для веб-дизайнеров',
    meta: 'Фокеев',
    note: 'Короткий курс, поднимает качество лендингов, которые делаешь без дизайнера. Можно по вечерам параллельно с Webflow.',
    hours: 7,
    value: 55,
    video: 6,
    factor: 1.2,
    units: 61,
    unitWord: 'уроков',
    unitsDone: 0,
    url: 'https://www.udemy.com/course/cniiaptv/',
  },
  {
    id: 'a-stepik-10-sites',
    track: 'A',
    kind: 'course',
    title: 'Верстаем 10 сайтов по макету из Figma в портфолио',
    meta: 'Фокеев · Stepik · 507 шагов',
    note: 'Единственный курс в библиотеке, который сам по себе даёт портфолио: десять готовых сайтов по макетам. Ровно этого треку A не хватало — заказы приходят с кейсов, а не с сертификатов. По одному сайту в неделю параллельно с WordPress, каждый готовый сразу в кейсы на verno-dev.com.',
    hours: 31,
    value: 95,
    units: 507,
    unitWord: 'шагов',
    unitsDone: 35,
    url: 'https://stepik.org/course/123120',
  },
  {
    id: 'a-stepik-wp-theme',
    track: 'A',
    kind: 'free',
    title: 'Сайт на WordPress: вёрстка и перенос на CMS',
    meta: 'Stepik · 307 шагов',
    note: 'Бесплатный курс про перенос своей вёрстки в тему WordPress. Пересекается с разделами Сокирки, поэтому по желанию: полезен, если хочешь пройти путь «макет → тема» до большого курса.',
    hours: 21,
    value: 35,
    optional: true,
    units: 307,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/113393',
  },
  {
    id: 'a-sales-kit',
    track: 'A',
    kind: 'practice',
    title: 'Набор продавца: ТЗ, договор, предоплата, шаблоны откликов',
    note: 'Шаблон технического задания, короткий договор-оферта, правило «50 % предоплаты», три шаблона отклика под лендинг / бизнес-сайт / магазин. Один вечер, а потом экономит часы на каждом заказе и режет число невыгодных клиентов.',
    hours: 4,
    value: 95,
  },
  {
    id: 'a-sochirca-1',
    track: 'A',
    kind: 'course',
    title: 'Весь WordPress и PHP, разделы 1–4',
    meta: 'Сокирка',
    note: 'База PHP (11 ч), кодекс темы (11 ч), практика темы (3 ч), кодекс плагинов (10 ч). Курс длится 244 ч — целиком не нужен, это ядро.',
    hours: 70,
    value: 85,
    video: 35,
    factor: 2,
    url: 'https://www.udemy.com/course/all-wordpress/',
  },
  {
    id: 'm-a-wp',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: доработки WordPress по коду',
    note: 'Правки тем и плагинов, хуки, интеграции — самая частая категория заказов на Kwork и FL.ru.',
    hours: 0,
  },
  {
    id: 'a-sochirca-2',
    track: 'A',
    kind: 'course',
    title: 'Весь WordPress и PHP, разделы 5–7',
    meta: 'Сокирка',
    note: 'Посадка HTML-шаблона на WP (15 ч), интернет-магазин на WooCommerce (12 ч), виджеты для Elementor (8 ч). Разделы 8–10 (WPBakery, SiteOrigin, Beaver) — мимо, 11–12 (155 ч практики) — как справочник под конкретный заказ.',
    hours: 70,
    value: 80,
    video: 35,
    factor: 2,
    url: 'https://www.udemy.com/course/all-wordpress/',
  },
  {
    id: 'm-a-shop',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: магазины на WooCommerce 15–65 тыс. ₽ и онлайн-школы на WP 20–55 тыс. ₽',
    note: 'Уже по твоему прайсу, а не по нижней планке.',
    hours: 0,
  },
  {
    id: 'a-kudlai-base',
    track: 'A',
    kind: 'course',
    title: 'PHP 8. От теории к практике',
    meta: 'Кудлай · справочник',
    note: 'Держи открытым рядом с первым разделом Сокирки и смотри только непонятное. Целиком (21 ч) — только если база PHP у Сокирки покажется слишком быстрой.',
    hours: 10,
    value: 30,
    video: 5,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/php-8-ua/',
  },
  {
    id: 'a-schiff',
    track: 'A',
    kind: 'course',
    title: 'Become a WordPress Developer',
    meta: 'Brad Schiff · EN · выборочно',
    note: 'Разделы 13–16 (REST API, AJAX), 18–19 (роли пользователей, пользовательский контент), 21 (деплой), 24 (Gutenberg-блоки на React). Это личные кабинеты для онлайн-школ на WP. Остальные 34 ч дублируют Сокирку.',
    hours: 24,
    value: 45,
    video: 12,
    factor: 2,
    url: 'https://www.udemy.com/course/become-a-wordpress-developer-php-javascript/',
  },
  {
    id: 'a-acf',
    track: 'A',
    kind: 'course',
    title: 'WordPress Theme Development with ACF',
    meta: 'Riani · EN',
    note: 'ACF постоянно встречается в кастомных сайтах для клиентов. Его же курс по Elementor для Themeforest — мимо: это про продажу тем на маркетплейсе.',
    hours: 16,
    value: 35,
    video: 11,
    factor: 1.5,
    optional: true,
    url: 'https://www.udemy.com/course/wordpress-advanced-theme-development-with-acf-acf-pro/',
  },
  {
    id: 'a-ai',
    track: 'A',
    kind: 'course',
    title: 'AI-разработка и создание AI-агентов',
    meta: 'Фокеев',
    note: 'Claude, основы LLM, агенты, ассистент в Telegram, сервисы автоматизации. Напрямую закрывает «AI-боты» в услугах — спрос есть, конкуренции меньше, чем в вёрстке.',
    hours: 10,
    value: 70,
    video: 6.3,
    factor: 1.5,
    url: 'https://www.udemy.com/course/ai-ai-cph/',
  },
  {
    id: 'm-a-ai',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: чат-боты на нейросетях для сайта и Telegram',
    note: 'Под «дополнительные услуги» с сайта: интеграции, AI-боты, сопровождение.',
    hours: 0,
  },
  {
    id: 'a-kudlai-oop',
    track: 'A',
    kind: 'course',
    title: 'PHP 8. ООП. Собственный MVC-фреймворк',
    meta: 'Кудлай',
    note: 'Фреймворк (16 ч): автозагрузка, роутинг, валидация, БД, авторизация, middleware, кеш. Потом CMS на нём (11 ч). Мост к Битриксу и к серьёзным плагинам WordPress. PHP после Сокирки ещё свежий — не откладывай.',
    hours: 54,
    value: 35,
    video: 26.8,
    factor: 2,
    url: 'https://www.udemy.com/course/php-8-framework/',
  },
  {
    id: 'a-bitrix',
    track: 'A',
    kind: 'free',
    title: '1С-Битрикс для разработчиков',
    meta: 'dev.1c-bitrix.ru/learning · academy.1c-bitrix.ru',
    note: 'Официальные бесплатные курсы: сначала «Разработчик», потом «Администратор» выборочно. Для практики — пробная версия «Управление сайтом». 40 ч — оценка, поправь по факту.',
    hours: 40,
    value: 75,
    url: 'https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43',
  },
  {
    id: 'm-a-bitrix',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: доработки и интеграции на Битриксе',
    note: 'Дорогие заказы русского рынка и мало исполнителей. Работает удалённо и после переезда.',
    hours: 0,
  },
  {
    id: 'a-getcourse',
    track: 'A',
    kind: 'free',
    title: 'GetCourse: администраторская часть',
    meta: 'Университет GetCourse · «Администратор GetCourse от А до Я»',
    note: 'Онлайн-школы на GetCourse заявлены на сайте, но курса в библиотеке нет. Проходи, когда придёт первый такой заказ — или заранее, если парсер показывает спрос. 15 ч — оценка.',
    hours: 15,
    value: 25,
    optional: true,
    url: 'https://getcourse.ru/course/admin',
  },
  {
    id: 'a-shopify-1',
    track: 'A',
    kind: 'course',
    title: 'Complete Shopify Course 2026, разделы 2–5',
    meta: 'M C, Dennis C · EN',
    note: 'Настройка и кастомизация магазина, настройки, выполнение заказов. Дропшиппинг, print-on-demand и реклама (разделы 9–15) — для владельцев магазинов, не для разработчика.',
    hours: 6,
    value: 15,
    video: 5,
    factor: 1.2,
    url: 'https://www.udemy.com/course/ultimate-shopify-course-beginner-to-shopify-expert-2024/',
  },
  {
    id: 'a-shopify-2',
    track: 'A',
    kind: 'course',
    title: 'The Complete Shopify Theme Development Course',
    meta: 'Rajinder Pal · EN',
    note: 'Shopify CLI, Liquid, секции темы, Alpine JS. Именно это продаётся как «разработка темы Shopify» на Upwork. В РФ Shopify почти не работает — это рынок зарубежных клиентов, важный с переездом.',
    hours: 32,
    value: 10,
    video: 15.8,
    factor: 2,
    url: 'https://www.udemy.com/course/the-complete-shopify-theme-development-course/',
  },
  {
    id: 'm-a-shopify',
    track: 'A',
    kind: 'milestone',
    title: 'В прайсе: Shopify для зарубежных клиентов',
    note: 'Открывается англоязычный рынок — Upwork и подобные.',
    hours: 0,
  },
  {
    id: 'a-ux',
    track: 'A',
    kind: 'course',
    title: 'UX-веб-дизайн в Figma с нейросетями',
    meta: 'Фокеев',
    note: 'Самый полезный из оставшихся дизайн-курсов: аргументированный редизайн для бизнес-клиентов — услуга «редизайн» с сайта. Figma Pro, Motion-дизайн, Photoshop, Illustrator — только если решишь продавать дизайн отдельно.',
    hours: 19,
    value: 25,
    video: 12.7,
    factor: 1.5,
    optional: true,
    url: 'https://www.udemy.com/course/ux-design-foundation/',
  },
  {
    id: 'a-multilink',
    track: 'A',
    kind: 'course',
    title: 'Мультиссылки и мини-сайты для Instagram',
    meta: 'SendPulse · 44 мин',
    note: 'Глянь за вечер, если по парсеру такие заказы попадаются, иначе пропускай.',
    hours: 1,
    value: 20,
    video: 0.7,
    optional: true,
    url: 'https://www.udemy.com/course/multilink-for-instagram/',
  },

  // ───────────────────────── Трек B — fullstack ─────────────────────────
  {
    id: 'b-stepik-js-full',
    track: 'B',
    kind: 'course',
    title: 'Полный курс по JavaScript — с нуля до результата',
    meta: 'Фокеев · Stepik · 223 из 224 шагов',
    note: 'Закрыт. База JavaScript есть: синтаксис, DOM, события, асинхронность на уровне курса. Дальше идёт углубление, а не повторение.',
    hours: 0,
    value: 90,
    done: true,
    url: 'https://stepik.org/course/130424',
  },
  {
    id: 'b-stepik-tvoy-js',
    track: 'B',
    kind: 'course',
    title: 'Твой JavaScript',
    meta: 'Тарасов · Stepik · 258 из 265 шагов',
    note: 'Задачный курс, закрыт на 97 %. Оставшиеся семь шагов — на один вечер.',
    hours: 0,
    value: 80,
    done: true,
    url: 'https://stepik.org/course/210361',
  },
  {
    id: 'b-stepik-react-full',
    track: 'B',
    kind: 'course',
    title: 'Полный курс по React JS — Redux, Router, Tailwind CSS',
    meta: 'Фокеев · Stepik · 334 из 334 шагов',
    note: 'Закрыт полностью. Основы React, Redux и роутинга есть, поэтому «React до middle» ниже — про паттерны и серверное состояние, а не про хуки с нуля.',
    hours: 0,
    value: 95,
    done: true,
    url: 'https://stepik.org/course/221235',
  },
  {
    id: 'b-js',
    track: 'B',
    kind: 'free',
    title: 'JavaScript вглубь',
    meta: 'learn.javascript.ru',
    note: 'Разделы «Продвинутая работа с функциями» и «Асинхронность»: замыкания, промисы, Event Loop, микро- и макрозадачи. Первый пункт чек-листа DeepSeek — без этого не пишется серверный код.',
    hours: 15,
    value: 90,
    url: 'https://learn.javascript.ru/advanced-functions',
  },
  {
    id: 'b-stepik-js-pro',
    track: 'B',
    kind: 'course',
    title: 'Самый полный курс по JavaScript для опытных программистов',
    meta: 'Stepik · 1141 шаг · пройдено 27 %',
    note: 'Куплен и пройден на четверть — не бросай, но и не ставь впереди Node. По желанию, по вечерам: замыкания, прототипы, асинхронность на глубину собеседования. «Твой JavaScript PRO» с того же аккаунта — дубль по темам, его в архив.',
    hours: 52,
    value: 45,
    optional: true,
    units: 1141,
    unitWord: 'шагов',
    unitsDone: 314,
    url: 'https://stepik.org/course/177315',
  },
  {
    id: 'b-node',
    track: 'B',
    kind: 'course',
    title: 'Node.js — полный курс',
    meta: 'Стащук · обновлён 03/2026',
    note: 'Архитектура Node, цикл событий, модули, fs/path/http/stream, Express и API. Раздел 3 «Краткий курс по JavaScript» пропускай — это твоя база. Express руками до Next.js, как советовал Google AI.',
    hours: 35,
    value: 90,
    video: 17.7,
    factor: 2,
    url: 'https://www.udemy.com/course/nodejs-ru/',
  },
  {
    id: 'b-sql',
    track: 'B',
    kind: 'free',
    title: 'SQL и PostgreSQL — основы',
    meta: 'Тренажёр ДВФУ · Stepik · 206 задач',
    note: 'Оба чек-листа ставят PostgreSQL в обязательный минимум. Интерактивный тренажёр ДВФУ — задачи без воды, на втором аккаунте уже 42 из 206. SELECT / JOIN / INSERT, связь users → orders, индексы на пальцах. «SQL для начинающих» (платный, 33 из 460) — справочник, «Введение в SQL» — дубль, в архив.',
    hours: 12,
    value: 90,
    units: 206,
    unitWord: 'задач',
    unitsDone: 42,
    url: 'https://stepik.org/course/63054',
  },
  {
    id: 'b-stepik-oop',
    track: 'B',
    kind: 'free',
    title: 'Миникурс: основы ООП для JS/TS и React-разработчика',
    meta: 'Stepik · 140 шагов',
    note: 'Классы, наследование, интерфейсы на языке фронтендера. Два вечера перед TypeScript — иначе generics и абстракции у Непомнящего пойдут тяжело.',
    hours: 3,
    value: 60,
    units: 140,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/245362',
  },
  {
    id: 'b-stepik-ts',
    track: 'B',
    kind: 'course',
    title: 'TypeScript для профессиональной разработки',
    meta: 'Непомнящий · Stepik · 232 шага',
    note: 'Куплен, пройдено 15 шагов. Основной курс по TypeScript вместо чтения handbook с нуля: типы, generics, narrowing, utility-типы, tsconfig на практике. Бесплатный «Программирование на TypeScript» Смирнова с первого аккаунта — дубль, не трать на него время.',
    hours: 14,
    value: 95,
    units: 232,
    unitWord: 'шагов',
    unitsDone: 15,
    url: 'https://stepik.org/course/121859',
  },
  {
    id: 'b-ts',
    track: 'B',
    kind: 'free',
    title: 'TypeScript — документация и handbook',
    note: 'Справочник к курсу Непомнящего: narrowing, utility-типы, tsconfig — читать по мере вопросов, а не подряд.',
    hours: 10,
    value: 40,
    optional: true,
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
  },
  {
    id: 'b-larichev',
    track: 'B',
    kind: 'course',
    title: 'Node.js — с нуля, основы и архитектура приложений',
    meta: 'Ларичев',
    note: 'Express, переход на TypeScript, DI (InversifyJS), Prisma поверх SQL, JWT, unit- и e2e-тесты. Единственный курс в наборе про TypeScript и архитектуру на бэкенде — проходи целиком.',
    hours: 36,
    value: 55,
    video: 18.1,
    factor: 2,
    url: 'https://www.udemy.com/course/nodejs-start/',
  },
  {
    id: 'b-tissen',
    track: 'B',
    kind: 'course',
    title: 'Fullstack: React + Node.js/Express — два проекта',
    meta: 'Тиссен',
    note: 'Два проекта целиком, фронт и бэк вместе. Здесь React встречается с твоим новым бэкендом: контроллеры, авторизация, связь по API.',
    hours: 48,
    value: 85,
    video: 24.1,
    factor: 2,
    url: 'https://www.udemy.com/course/fullstack-react-nodejsexpress/',
  },
  {
    id: 'm-b-api',
    track: 'B',
    kind: 'milestone',
    title: 'Свой API + React-фронт: можно брать интеграции и личные кабинеты на Node',
    note: 'Первые fullstack-заказы под «дополнительные услуги» с сайта.',
    hours: 0,
  },
  {
    id: 'b-mongo',
    track: 'B',
    kind: 'course',
    title: 'MongoDB — полный курс',
    meta: 'Стащук',
    note: 'После PostgreSQL, не вместо: Google AI прямо советует начинать с реляционной базы. Mongo нужна, потому что на ней держатся MERN-проекты и половина курсов по Node.',
    hours: 13,
    value: 40,
    video: 8.7,
    factor: 1.5,
    url: 'https://www.udemy.com/course/mongodb-ru/',
  },
  {
    id: 'b-socketio',
    track: 'B',
    kind: 'course',
    title: 'SocketIO and TypeScript',
    meta: 'Bradley · EN',
    note: 'WebSockets из чек-листа DeepSeek плюс редкая вещь: деплой руками на VPS — nginx, домен, SSL. Тот самый «Linux, SSH, nginx, логи».',
    hours: 5,
    value: 45,
    video: 2.9,
    factor: 1.5,
    url: 'https://www.udemy.com/course/typescript-socketio/',
  },
  {
    id: 'b-stepik-docker',
    track: 'B',
    kind: 'free',
    title: 'Docker для начинающих + практический опыт',
    meta: 'Stepik · 128 шагов',
    note: 'Бесплатное введение перед курсом Кочергина, по желанию: образы, контейнеры, тома. «Знакомство с Docker» с первого аккаунта короче и целиком внутри этого.',
    hours: 5,
    value: 35,
    optional: true,
    units: 128,
    unitWord: 'шагов',
    unitsDone: 1,
    url: 'https://stepik.org/course/123300',
  },
  {
    id: 'b-docker',
    track: 'B',
    kind: 'course',
    title: 'Docker и Docker Compose — деплой проекта с нуля',
    meta: 'Кочергин',
    note: 'Dockerfile, API + база + фронт в Compose, nginx, сети, деплой на сервер. Сразу после курса упакуй в Docker то, что сделал у Тиссена.',
    hours: 8,
    value: 85,
    video: 3.7,
    factor: 2,
    url: 'https://www.udemy.com/course/docker-and-docker-compose/',
  },
  {
    id: 'm-b-deploy',
    track: 'B',
    kind: 'milestone',
    title: 'Умеешь поднять проект на VPS в Docker с nginx и SSL',
    note: 'Блок DevOps из чек-листа закрыт на уровне «сам разворачиваю то, что написал».',
    hours: 0,
  },
  {
    id: 'b-next-wp',
    track: 'B',
    kind: 'course',
    title: 'Next JS & WordPress: headless-сайты',
    meta: 'Phillips · EN · обновлён 07/2026',
    note: 'Next.js (pages router + раздел про переход на App Router), GraphQL, headless WordPress с ACF, Tailwind, деплой на Vercel. Связывает WordPress из трека A с fullstack.',
    hours: 17,
    value: 60,
    video: 8.4,
    factor: 2,
    url: 'https://www.udemy.com/course/next-js-wordpress/',
  },
  {
    id: 'b-nextpizza',
    track: 'B',
    kind: 'free',
    title: 'NextPizza',
    meta: 'Archakov Blog · YouTube',
    note: 'Next.js App Router, TypeScript, Prisma, PostgreSQL, авторизация, корзина, оплата — курс из рекомендаций Google AI. Сюда приходишь уже с Express и SQL в руках, поэтому Server Actions не выглядят магией. 40 ч — оценка, длину плейлиста проверь.',
    hours: 40,
    value: 70,
    url: 'https://www.youtube.com/watch?v=GUwizGbY4cc',
  },
  {
    id: 'b-cicd',
    track: 'B',
    kind: 'free',
    title: 'GitHub Actions — CI/CD для своего проекта',
    note: 'Линт + тесты + сборка Docker-образа на push. Хватит документации GitHub и одного вечера. Этот сайт, кстати, деплоится через такой же workflow.',
    hours: 5,
    value: 75,
    url: 'https://docs.github.com/ru/actions',
  },
  {
    id: 'b-react-mid',
    track: 'B',
    kind: 'free',
    title: 'React до middle',
    meta: 'документация Redux Toolkit, react.dev',
    note: 'Redux Toolkit + RTK Query, memo / useMemo / useCallback, кастомные хуки, виртуализация списков. Не отдельный курс, а требования к коду пет-проекта — читаешь и сразу применяешь.',
    hours: 10,
    value: 90,
    url: 'https://redux-toolkit.js.org/',
  },
  {
    id: 'b-stepik-react-pro',
    track: 'B',
    kind: 'course',
    title: 'React для современных веб-приложений',
    meta: 'Непомнящий · Stepik · 201 шаг',
    note: 'Куплен, 6 шагов пройдено. Второй заход в React после курса Фокеева — уже на уровне требований вакансий: композиция, производительность, работа с сервером. Проходить рядом с пет-проектом и сразу переносить в его код.',
    hours: 13,
    value: 80,
    units: 201,
    unitWord: 'шагов',
    unitsDone: 6,
    url: 'https://stepik.org/course/114197',
  },
  {
    id: 'b-stepik-redux',
    track: 'B',
    kind: 'course',
    title: 'Redux для управления состоянием React-приложений',
    meta: 'Непомнящий · Stepik · 224 шага',
    note: 'По желанию: Redux уже был у Фокеева, а для пет-проекта хватит RTK Query из «React до middle». Куплен — вернись, если на собеседовании начнут спрашивать middleware и нормализацию стора.',
    hours: 11,
    value: 30,
    optional: true,
    units: 224,
    unitWord: 'шагов',
    url: 'https://stepik.org/course/113714',
  },
  {
    id: 'b-testing',
    track: 'B',
    kind: 'free',
    title: 'Тестирование React: Jest + React Testing Library',
    meta: 'testing-library.com · jestjs.io',
    note: 'Единственная дыра стека относительно React-вакансий: в библиотеке нет ни одного курса по тестам. Цель — покрыть пет-проект: unit-тесты утилит, тесты компонентов через RTL, один интеграционный на ключевой сценарий, запуск в GitHub Actions.',
    hours: 8,
    value: 95,
    url: 'https://testing-library.com/docs/react-testing-library/intro/',
  },
  {
    id: 'b-perf',
    track: 'B',
    kind: 'free',
    title: 'Производительность React: профилировщик, code splitting, Core Web Vitals',
    meta: 'react.dev · DevTools Performance · Lighthouse',
    note: 'Курса не нужно — замеры на своём пет-проекте: React Profiler и вкладка Performance, мемоизация только там, где профилировщик показал лишние перерисовки, lazy и code splitting по маршрутам, картинки и шрифты, Lighthouse не ниже 90 по всем четырём метрикам. Цифры «до и после» — в README: это отдельный аргумент на собеседовании.',
    hours: 8,
    value: 70,
    url: 'https://react.dev/reference/react/Profiler',
  },
  {
    id: 'b-pet',
    track: 'B',
    kind: 'practice',
    title: 'Пет-проект: парсер заказов как продукт',
    meta: 'Next.js App Router · PostgreSQL/Prisma · Telegram · Docker · GitHub Actions',
    note: 'У тебя уже есть парсер бирж с ежедневной сводкой. Перепиши его в продукт: фильтры по стеку, уведомления в Telegram, деплой в Docker на VPS, CI. Одновременно портфолио, инструмент для заказов и кейс «интеграции» на сайте. Критерии приёмки: TypeScript в режиме strict без единого any, серверное состояние через RTK Query или TanStack Query, тесты и линт в CI, публичный репозиторий с README про архитектуру и живое демо по ссылке. Вариант Б для iGaming — карточная игра «21» на React + PixiJS/GSAP и Node + Socket.IO.',
    hours: 100,
    value: 100,
  },
  {
    id: 'm-b-portfolio',
    track: 'B',
    kind: 'milestone',
    title: 'Живой проект на Next.js + Node + PostgreSQL + Docker с публичным репозиторием',
    note: 'Главная строчка в резюме fullstack-джуна и главный кейс на verno-dev.com. Можно откликаться на удалёнку.',
    hours: 0,
  },
  {
    id: 'b-stepik-interview',
    track: 'B',
    kind: 'free',
    title: 'Проверка знаний и подготовка к собеседованию по JavaScript',
    meta: 'Stepik · 315 задач',
    note: 'Лучший бесплатный тренажёр под интервью, лежит на обоих аккаунтах нетронутым. После пет-проекта: по 20–30 задач в день перед откликами на вакансии, слабые темы — обратно в «JavaScript вглубь».',
    hours: 6,
    value: 85,
    units: 315,
    unitWord: 'задач',
    unitsDone: 1,
    url: 'https://stepik.org/course/189305',
  },
  {
    id: 'b-mock-interviews',
    track: 'B',
    kind: 'practice',
    title: 'Пробные собеседования: три-пять моков',
    meta: 'getmentor.dev · Solvery · pramp',
    note: 'Тренажёр проверяет теорию, моки — умение объяснять решения вслух. Три-пять интервью с практикующими разработчиками: бесплатные менторы на getmentor.dev, платные на Solvery, peer-to-peer на pramp (на английском). После каждого — список пробелов, и только потом отклики на вакансии.',
    hours: 6,
    value: 80,
    url: 'https://getmentor.dev/',
  },
  {
    id: 'b-nest',
    track: 'B',
    kind: 'free',
    title: 'NestJS: «Облачное хранилище»',
    meta: 'Archakov Blog · Next.js + NestJS + TypeScript',
    note: 'Оба чек-листа говорят «отложить NestJS» — сюда приходишь после пет-проекта. 40 ч — оценка.',
    hours: 40,
    value: 35,
    optional: true,
    url: 'https://www.youtube.com/watch?v=_oR1p79t6gw',
  },
  {
    id: 'b-hardening',
    track: 'B',
    kind: 'free',
    title: 'Безопасность, логирование, основы system design',
    meta: 'OWASP Top 10 · Winston/Pino · Sentry',
    note: 'Из «дополнительных слоёв» DeepSeek: CSRF/XSS/SQL-инъекции, rate limiting, CORS, структурные логи через Pino и алерты в Sentry. Не по желанию: на middle-собеседовании спрашивают, как ты узнаёшь о падении в проде. Читаешь и добавляешь в пет-проект — так это и запоминается.',
    hours: 10,
    value: 65,
    url: 'https://owasp.org/www-project-top-ten/',
  },
  {
    id: 'b-pixi',
    track: 'B',
    kind: 'free',
    title: 'PixiJS + GSAP',
    meta: 'если iGaming всерьёз',
    note: 'Специализация из чек-листа DeepSeek: 2D-рендеринг, анимации, канвас. Берётся вместе с вариантом Б пет-проекта (карточная игра). 30 ч — оценка.',
    hours: 30,
    value: 15,
    optional: true,
    url: 'https://pixijs.com/8.x/guides/getting-started/intro',
  },
  {
    id: 'b-rn',
    track: 'B',
    kind: 'course',
    title: 'React Native 2026 + React Native: Advanced Concepts',
    meta: 'Sawy, Grider · EN · 41 ч видео',
    note: 'Только если мобильная разработка станет целью. Курс Grider старый — проверь дату обновления, прежде чем тратить время.',
    hours: 80,
    value: 20,
    video: 41,
    factor: 2,
    optional: true,
    url: 'https://www.udemy.com/course/the-best-react-native-course/',
  },
]

export const HABITS: Habit[] = [
  { track: 'A', time: '1 ч/день', text: 'Биржи: отклики по сводке парсера, переписка, оценка задач' },
  { track: 'A', time: 'каждый заказ', text: 'Кейс на verno-dev.com и отзыв на бирже — портфолио продаёт лучше курсов' },
  { track: 'A', time: '1 раз/нед', text: 'Свериться с парсером: какой стек реально заказывают — и переставить курсы, если картина другая' },
  { track: 'B', time: '20–30 мин/день', text: 'Codewars 6–7 kyu, позже LeetCode easy — алгоритмы для собеседований' },
  { track: 'B', time: '30 мин/день', text: 'Английский до B2: документация и видео по теме в оригинале, англоязычные курсы без субтитров' },
  { track: 'B', time: 'всегда', text: 'Читать документацию в первоисточнике, а не пересказы' },
]

import remindersJson from './reminders.json'

export interface Reminder {
  id: string
  /** ISO-дата разового напоминания (наступает с этой даты) */
  date?: string
  /** Повторяющееся: weekly — по дню недели, monthly — по числу месяца */
  repeat?: 'weekly' | 'monthly'
  /** День недели для weekly: 1 = понедельник … 7 = воскресенье */
  weekday?: number
  /** Число месяца для monthly: 1–28 */
  day?: number
  title: string
  text?: string
  link?: { hash: string; label: string }
}

/** Общие напоминания живут в reminders.json — его же читает workflow телеграм-бота */
export const REMINDERS: Reminder[] = remindersJson as Reminder[]

export const SKIPPED = [
  { title: 'WordPress Development 2026', meta: 'Madani · 14,5 ч', why: 'дубль Сокирки и Schiff; headless-часть — при заказе' },
  { title: 'WordPress Theme Development for Themeforest with Elementor', meta: 'Riani · 21,4 ч', why: 'продажа тем на маркетплейсе, не фриланс' },
  { title: 'Весь WordPress и PHP, разделы 8–12', meta: 'Сокирка · 172 ч', why: 'справочник под конкретный заказ' },
  { title: 'Become a WordPress Developer, остальные разделы', meta: 'Schiff · 34 ч', why: 'дубль' },
  { title: 'Complete Shopify Course, разделы 9–15', meta: '10 ч', why: 'дропшиппинг и реклама — для владельцев магазинов' },
  { title: 'Веб-дизайн в Figma — продвинутый, Motion-дизайн, Photoshop ×2, Illustrator', meta: '55 ч', why: 'разработчику не нужны, только если продавать дизайн отдельно' },
  { title: 'PHP 8. От теории к практике, остаток', meta: 'Кудлай · 16 ч', why: 'если база Сокирки окажется быстрой' },
]
